# Generated by Django 2.0.3 on 2020-09-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cc_num', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exp_date', models.CharField(max_length=4)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_code', models.CharField(max_length=3)),
                ('trans_id', models.TextField()),
            ],
            options={
                'verbose_name': 'transactions',
                'verbose_name_plural': 'transactions',
                'db_table': 'transactions',
            },
        ),
    ]
